FROM python:3.10.0-alpine3.15
WORKDIR /app
COPY requirements_html.txt .
RUN pip install -r requirements_html.txt
COPY src_html_generator src
EXPOSE 5001
ENTRYPOINT ["python", "./src/html_generator.py"]