apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      protocol: TCP
  selector:
    app: my-front-end
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-front-end-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-front-end
  template:
    metadata:
      labels:
        app: my-front-end
    spec:
      containers:
      - name: my-front-end
        image: my_front_end4:0.15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000